import 'dotenv/config';
import bcrypt from 'bcryptjs';
import cors from 'cors';
import express, { NextFunction, Request, Response } from 'express';
import rateLimit from 'express-rate-limit';
import jwt from 'jsonwebtoken';
import { createClient } from 'redis';
import { Pool } from 'pg';
import { createServer } from 'node:http';
import { Server } from 'socket.io';
import { z } from 'zod';

const env = z.object({ DATABASE_URL: z.string().url(), JWT_SECRET: z.string().min(20), REDIS_URL: z.string().url(), PORT: z.coerce.number().default(4000), CORS_ORIGIN: z.string().url().default('http://localhost:5173') }).parse(process.env);
const pool = new Pool({ connectionString: env.DATABASE_URL });
const redis = createClient({ url: env.REDIS_URL });
redis.on('error', (error) => console.error('Redis error', error));
const app = express(); const server = createServer(app); const io = new Server(server, { cors: { origin: env.CORS_ORIGIN } });
app.use(cors({ origin: env.CORS_ORIGIN })); app.use(express.json()); app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: 'draft-7', legacyHeaders: false }));
type Role = 'ADMIN' | 'DISPATCHER' | 'OPERATOR'; type Identity = { id: string; role: Role; email: string };
declare global { namespace Express { interface Request { identity?: Identity } } }
function authenticate(req: Request, res: Response, next: NextFunction) { const value = req.header('authorization'); if (!value?.startsWith('Bearer ')) return res.status(401).json({ error: 'Authentication required' }); try { req.identity = jwt.verify(value.slice(7), env.JWT_SECRET) as Identity; next(); } catch { res.status(401).json({ error: 'Invalid or expired token' }); } }
function allow(...roles: Role[]) { return (req: Request, res: Response, next: NextFunction) => !req.identity || !roles.includes(req.identity.role) ? res.status(403).json({ error: 'Insufficient permissions' }) : next(); }
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) });
app.get('/health', async (_req, res) => { await pool.query('SELECT 1'); res.json({ status: 'ok' }); });
app.post('/api/v1/auth/login', async (req, res, next) => { try { const body = loginSchema.parse(req.body); const { rows } = await pool.query('SELECT id,email,password_hash,role,is_active FROM users WHERE email = $1', [body.email.toLowerCase()]); const user = rows[0]; if (!user || !user.is_active || !(await bcrypt.compare(body.password, user.password_hash))) return res.status(401).json({ error: 'Invalid credentials' }); const identity: Identity = { id: user.id, email: user.email, role: user.role }; const token = jwt.sign(identity, env.JWT_SECRET, { expiresIn: '15m' }); const refreshToken = jwt.sign(identity, env.JWT_SECRET, { expiresIn: '7d' }); await redis.set(`refresh:${user.id}:${refreshToken}`, '1', { EX: 604800 }); res.json({ token, refreshToken, user: identity }); } catch (error) { next(error); } });
app.post('/api/v1/auth/refresh', async (req, res, next) => { try { const refreshToken = z.object({ refreshToken: z.string() }).parse(req.body).refreshToken; const identity = jwt.verify(refreshToken, env.JWT_SECRET) as Identity; if (!(await redis.get(`refresh:${identity.id}:${refreshToken}`))) return res.status(401).json({ error: 'Session expired' }); res.json({ token: jwt.sign(identity, env.JWT_SECRET, { expiresIn: '15m' }) }); } catch (error) { next(error); } });
app.get('/api/v1/dashboard/metrics', authenticate, async (_req, res, next) => { try { const { rows } = await pool.query('SELECT active_nodes,operational_rate,system_load_ms,recorded_at FROM system_metrics ORDER BY recorded_at DESC LIMIT 1'); res.json(rows[0] ?? { active_nodes: 0, operational_rate: 0, system_load_ms: 0 }); } catch (error) { next(error); } });
app.get('/api/v1/operations/logs', authenticate, async (req, res, next) => { try { const query = z.object({ page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().min(1).max(100).default(20), status: z.enum(['SUCCESS','PENDING','FAILED']).optional() }).parse(req.query); const where = query.status ? 'WHERE status = $1' : ''; const values = query.status ? [query.status, query.limit, (query.page - 1) * query.limit] : [query.limit, (query.page - 1) * query.limit]; const { rows: totalRows } = await pool.query(`SELECT count(*) FROM operation_logs ${where}`, query.status ? [query.status] : []); const { rows } = await pool.query(`SELECT operation_id,task_description,input_size,processing_time_ms,status,created_at FROM operation_logs ${where} ORDER BY created_at DESC LIMIT $${query.status ? 2 : 1} OFFSET $${query.status ? 3 : 2}`, values); res.json({ data: rows, page: query.page, limit: query.limit, total: Number(totalRows[0].count) }); } catch (error) { next(error); } });
app.post('/api/v1/operations/execute', authenticate, allow('ADMIN','DISPATCHER'), async (req, res, next) => { try { const body = z.object({ taskDescription: z.string().min(3).max(1000), inputSize: z.string().max(50).optional() }).parse(req.body); const operationId = `OP-${crypto.randomUUID().slice(0, 8).toUpperCase()}`; const started = performance.now(); await new Promise(resolve => setTimeout(resolve, 350)); const elapsed = Math.round(performance.now() - started); const { rows } = await pool.query('INSERT INTO operation_logs (operation_id,task_description,input_size,processing_time_ms,status,executed_by) VALUES ($1,$2,$3,$4,$5,$6) RETURNING operation_id,status,processing_time_ms,created_at', [operationId, body.taskDescription, body.inputSize ?? null, elapsed, 'SUCCESS', req.identity!.id]); const metrics = { active_nodes: 12, operational_rate: 99.8, system_load_ms: Math.floor(35 + Math.random() * 35) }; await pool.query('INSERT INTO system_metrics (active_nodes,operational_rate,system_load_ms) VALUES ($1,$2,$3)', [metrics.active_nodes, metrics.operational_rate, metrics.system_load_ms]); io.emit('metrics:update', metrics); res.status(201).json(rows[0]); } catch (error) { next(error); } });
app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { if (error instanceof z.ZodError) return res.status(400).json({ error: 'Invalid request', details: error.flatten() }); console.error(error); res.status(500).json({ error: 'Unexpected server error' }); });
async function boot() { await redis.connect(); server.listen(env.PORT, () => console.log(`CWROS API listening on :${env.PORT}`)); } boot().catch(error => { console.error(error); process.exit(1); });
